message='Hello World'
print(message)
print("-----------------------------------------------------")
print("To display the first character")
print(message[0])
print("-----------------------------------------------------")
print("To display the first to fourth character")
print(message[0:5])
print("-----------------------------------------------------")
print("To display till fourth character")
print(message[:5])
print("-----------------------------------------------------")
print("To display till fifth character")
print(message[6:])
print("-----------------------------------------------------")
print("lower() -> To print lower case letters")
print(message.lower())
print("-----------------------------------------------------")
print("upper() -> To print upper case letters")
print(message.upper())
print("-----------------------------------------------------")
print("count() -> Takes the entire string passed as an argument")
print(message.count('Hello'))
print(message.count('World'))
print(message.count('o'))
print("-----------------------------------------------------")
print("find() -> To find the starting position of the string that is passed as an argument")
print(message.find('Hello'))
print(message.find('World'))
print(message.find('o'))
print(message.find('universe'))
print("-----------------------------------------------------")
print("replace() -> To replace the given string with the another string")
print(message.replace('World', 'Universe'))
print(message.replace('Earth','Jack'))
print(message.replace('Hello','Bye'))
print("-----------------------------------------------------")
print("To replace a value inside a variable")
message = message.replace('World', 'Universe')
print("New value:", message)
print("-----------------------------------------------------")
greeting='Hello'
name='Stuart'
message1 = greeting +" "+ name
print(message1)
print("-----------------------------------------------------")
print("Placeholder:")
message2= '{}, {}. Welcome!'.format(greeting, name)
print(message2)
print("-----------------------------------------------------")
print("f string for python version > 3.6: ")
message3 = f'{greeting}, {name.upper()}. Welcome!'
print(message3)
print("-----------------------------------------------------")
print("help() function -> you need to run the help function on a string class then only it will work.")
print(help(str))
print("-----------------------------------------------------")
print(help(str.lower))
print("-----------------------------------------------------")

