print("-----------------------------------------------------")
print("List")
print("-----------------------------------------------------")
print("--1. Definition--")
print("A list is a mutable, ordered collection of items.")
print("Defined using square brackets [].")
fruits = ["apple", "banana", "cherry"]
print(fruits)
print("-----------------------------------------------------")
print("--2. Support multiple data types--")
print("A list can hold different data types (int, float, string, even other lists).")
mixed = [1, "hello", 3.14, [2, 4]]
print(mixed)
print("-----------------------------------------------------")
print("--3. Indexing and Slicing--")
print("Lists are zero-indexed")
print("You can access or slice elements using index positions.")
print("To display the FIRST element in the list:")
print(fruits[0])
print("To display the LAST element in the list:")
print(fruits[-1])
print("To display from second -> fourth elements in the list:")
print(fruits[1:3])
print(" If you dont know how many items are present in the list. To display from second -> last element in the list:")
print(fruits[1:])
print(" If you dont know how many items are present in the list. To display from second last -> first element in the list:")
print(fruits[:-1])
print("-----------------------------------------------------")
print("--4. Mutable--")
print("You can change, add, or remove elements after the list is created.")
fruits[1] = "orange"
print("Current list of fruits ->", fruits)
print("-----------------------------------------------------")
print("--4.1 append() method --")
fruits.append("grape")
print("Current list of fruits after append() is performed ->", fruits)
print("-----------------------------------------------------")
print("--4.2 remove() method --")
fruits.remove("apple")
print("Current list of fruits after remove() is performed ->", fruits)
print("-----------------------------------------------------")
print("--4.3 insert() method --")
fruits.insert(0,'Banana')
print("Current list of fruits after inserting a fruit in the first position using insert() ->", fruits)
fruits.insert(-1,'Apricot')
print("Current list of fruits after inserting a fruit in the last position using insert() ->", fruits)
print("-----------------------------------------------------")
print("--4.4 insert()  method -> Adding list inside another list using insert()--")
fruits_2=['Pomegranete','Kiwi']
fruits.insert(2,fruits_2)
print("Adding a list into another list using insert() method -> ", fruits)
print("To display the list inside another list using index position ->", fruits[2])
print("-----------------------------------------------------")
print("--4.5 append()  method -> Adding list inside another list using append()--")
fruits_3=['Pineapple','Strawberry','Blueberry']
fruits.append(fruits_3)
print("Adding a list into another list using append() method -> ", fruits)
print("To display the list inside another list using index position ->", fruits[-1])
print("Last element of the list -> 0 index position: ", fruits[-1][0])
print("Last element of the list -> 1 index position: ", fruits[-1][1])
print("Last element of the list -> 2 index position: ", fruits[-1][2])
print("Last element of the list -> last index position: ", fruits[-1][-1])
print("Last element of the list -> second last index position: ", fruits[-1][-2])
print("Last element of the list -> third last index position: ", fruits[-1][-3])
print("-----------------------------------------------------")
print("--4.6 extend()  method -> Adding list inside another list using extend()--")
fruits_4=['Rambutan','Lucuma','Cempedak','Chempedak']
fruits.extend(fruits_4)
print("When we use extend method. It will add all the values from the given list to the existing list")
print(fruits)
print("-----------------------------------------------------")
print("SCENARIO 1: remove() method  -> To remove last elements in the list using remove() --")
print("remove() -> This will remove the specified element specified in the remove() method")
fruits_5=['qwerty','qwerty']
print("After adding the fruits using extends() method.")
fruits.extend(fruits_5)
print(fruits)
fruits.remove('qwerty')
print(fruits)
print("NOTE -> remove() method will not remove all elemets having the same name. If there are many it will remove the elemnet belonging to the last index.")
fruits.remove('qwerty')
print(fruits)
print("-----------------------------------------------------")
print("SCENARIO 2: pop() method -> To remove last elements in the list using pop() --")
print("pop() -> This will pop the last element in the list")
fruits.pop()
print(fruits)
fruits.pop()
print(fruits)
fruits.pop()
print(fruits)
fruits.pop()
print(fruits)
fruits.pop()
print(fruits)
print("-----------------------------------------------------")
print("SCENARIO 3: sort()  method -> To sort the elements in the the list using sort() --")
veggies=['Cucumber','Carrot','Tomatoes','Potatoes','Radishes','Cauliflower']
print("sort() -> To sort the list in alphabetic order")
veggies.sort()
print(veggies)
print("reverse() -> To sort the list in reverse order")
veggies.reverse()
print(veggies)
print("sort(reverse=True) -> To sort the list in descending order")
veggies.sort(reverse=True)
print(veggies)
print("sort(reverse=False) -> To sort the list in ascending order")
veggies.sort(reverse=False)
print(veggies)
print("-----------------------------------------------------")
print("SCENARIO 4: sorted() fnc -> To sort the elements in the the list using sorted() fnc --")
courses=['History', 'Math', 'Physics','CompSci']
sorted_courses=sorted(courses)
print(sorted_courses)
print("-----------------------------------------------------")
print("SCENARIO 5: min() and max() fnc -> To sort the elements in the the list using sorted() fnc --")
nummies=[1,101,23,43,56,782134]
min_nummies=min(nummies)
print("min() -> Minimum number in the list -> ",min_nummies)
max_nummies=max(nummies)
print("max() -> Maximum number in the list -> ",max_nummies)
print("-----------------------------------------------------")
print("SCENARIO 6: sum() fnc -> To calculate the sum of the list using sum() fnc --")
sum_nummies=sum(nummies)
print("sum() -> To calculate the sum of the list -> ",sum_nummies)
print("-----------------------------------------------------")
print("SCENARIO 7: index() method -> To find the value of the index in the list using index() method --")
print(nummies)
print(nummies.index(43))
print(nummies.index(782134))
print("-----------------------------------------------------")
print("SCENARIO 8: To check if the number is present in the list or not --")
print(44 in nummies) #False
print(782134 in nummies) #True
print("-----------------------------------------------------")
print("SCENARIO 9: Loop through each item in the list using `for` loop")
for item in nummies:
    print(item)
print("-----------------------------------------------------")
print("SCENARIO 10: Loop through each item in the list to display index and value")
for index, course in enumerate(nummies):
    print(index,course)
print("-----------------------------------------------------")
print("SCENARIO 11: Loop through each item in the list with a starting position -> to display index and value")
for index, course in enumerate(nummies, start=1):
    print(index,course)
print("-----------------------------------------------------")
print("SCENARIO 12: join() method")
courses=['Geography','Maths','Science','Social Science','History']
course_str='-'.join(courses)
print(course_str)
course_str='*'.join(courses)
print(course_str)
print("-----------------------------------------------------")
print("SCENARIO 13: split() method")
print("In Python, the split() method is used to split a string into a list of substrings based on a separator (also called a delimiter).")
new_list = course_str.split('*')
print(new_list)
print("-----------------------------------------------------")
print("SCENARIO 14: List is mutable")
list_1=['History','Math','Physics','CompSci']
list_2=list_1
print(list_1)
print(list_2)
list_1[0]='Art'
print(list_1)
print(list_2)
print("-----------------------------------------------------")






